import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import ClientProviders from "./providers.client";
import ServerProviders from "./providers.server";

export const metadata: Metadata = {
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
	title: "Create T3 App",
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable}`} lang="en">
			<body>
				<ServerProviders>
					<ClientProviders>
						{children}
					</ClientProviders>
				</ServerProviders>
			</body>
		</html>
	);
}
